# Generated by Django 4.2 on 2024-05-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('Apointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
                'ordering': ['service_id'],
            },
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('therapist_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Therapist',
                'verbose_name_plural': 'Tharapists',
                'ordering': ['therapist_id'],
            },
        ),
        migrations.CreateModel(
            name='User_mobile',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Dateofbirth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('ndis_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SubUser',
            fields=[
                ('sub_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('ndis_number', models.CharField(max_length=20)),
                ('parent_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_api_user.user_mobile')),
            ],
            options={
                'verbose_name': 'Subuser',
                'verbose_name_plural': 'Subuser',
                'ordering': ['sub_user_id'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('Provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=100)),
                ('Apointment', models.ManyToManyField(blank=True, to='mobile_api_user.apointment')),
                ('Therapist_add', models.ManyToManyField(blank=True, to='mobile_api_user.therapist')),
                ('services', models.ManyToManyField(blank=True, related_name='therapy', to='mobile_api_user.service')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=5, null=True)),
                ('weight', models.CharField(blank=True, max_length=5, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
                ('data_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_api_user.user_mobile')),
            ],
            options={
                'verbose_name': 'CustomerDetails',
                'verbose_name_plural': 'CustomerDetails',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='apointment',
            name='User_mobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_api_user.user_mobile'),
        ),
    ]
