# Generated by Django 4.2 on 2024-05-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_mobile',
            name='last_login',
        ),
    ]
