# Generated by Django 4.2 on 2024-05-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0002_remove_user_mobile_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_mobile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
