# Generated by Django 4.2 on 2024-05-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0003_user_mobile_last_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_mobile',
            table='mobile_api_user_user_mobile',
        ),
    ]
