# Generated by Django 4.2 on 2024-05-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0004_alter_user_mobile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='apointment',
            name='Therapist_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apointment',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
