# Generated by Django 4.2 on 2024-05-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0005_apointment_therapist_name_apointment_provider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='Booked',
            field=models.BooleanField(default=False),
        ),
    ]
