# Generated by Django 4.2 on 2024-05-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0006_provider_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
