# Generated by Django 4.2 on 2024-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0007_provider_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='Booked',
        ),
        migrations.AddField(
            model_name='apointment',
            name='Booked',
            field=models.BooleanField(default=False),
        ),
    ]
