# Generated by Django 4.2 on 2024-05-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0008_remove_provider_booked_apointment_booked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdetails',
            options={'managed': False, 'ordering': ['id'], 'verbose_name': 'CustomerDetails', 'verbose_name_plural': 'CustomerDetails'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False, 'ordering': ['service_id'], 'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='subuser',
            options={'managed': False, 'ordering': ['sub_user_id'], 'verbose_name': 'Subuser', 'verbose_name_plural': 'Subuser'},
        ),
        migrations.AlterModelOptions(
            name='therapist',
            options={'managed': False, 'ordering': ['therapist_id'], 'verbose_name': 'Therapist', 'verbose_name_plural': 'Tharapists'},
        ),
        migrations.AlterModelOptions(
            name='user_mobile',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='apointment',
            name='Service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
