# Generated by Django 4.2 on 2024-06-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0011_service_therapist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apointment_unique_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='therapymobile_number', to='mobile_api_user.service'),
        ),
    ]
