# Generated by Django 4.2 on 2024-06-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0012_appointment_booked_alter_provider_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_mobile',
            options={'managed': True},
        ),
    ]
